### PR TITLE
Update images and message FirstTimeWizard.

### PR DESCRIPTION
**Pull request by varlesh**
Please check, because i'm not programmer :)

### CODE REVIEW

**Comment by varlesh** [comment]
Or change message to:

```
Now you can enable or disable modules on KDE Connect Settings
Indicator already added to autostart.
```

**Comment by Bajoja** [comment]
It's a great ideia update the first time wizard images, but we need this as a real scenario, so unpair your phone and do this again like it's the first time you gonna pair your phone, and i can't see the indicator-kde connect on startup aplicatication.
Can you correct this. ;)

**Comment by varlesh** [comment]
Maybe you correct this, because i'm bad know engish

**Comment by Bajoja** [comment]
I'm sorry, but i think ubuntu represents the best environment for doing these screenshot along with the icons that you have designed, and you understand better this than me.

When I said do this again, I was referring that for the first time the user will use it to appear only the phone name,  the phrase "Device Reachable but Not Trusted"  and pair button.

indicator

**Comment by varlesh** [comment]
haha, ok i replace this screen soon... Please sorry, i'm stupid :)

**Comment by varlesh** [comment]
done

**Comment by Bajoja** [comment]
Great ;)
One more favor please, the default icons on "icons/default" folder, i don't like them, can you draw something universal to replace them?

**Comment by varlesh** [comment]
Ok, later only

**Pull request merged**
