### PR TITLE
Fixed accented character bug and changed the port to 8013

### PR DESCRIPTION
**Pull request by OzymandiasTheGreat**

### CODE REVIEW

**Comment by Bajoja** [comment]
@OzymandiasTheGreat  what you think about the sync button icon, aesthetically I do not think it looks beautiful, there is another on gtk sources that can be used like the reload button or do you think it should  stay like is it?

**Comment by OzymandiasTheGreat** [comment]
@Bajoja I don't have strong opinions on this. I'm using numix icon theme, so current icon looks fine for me, but if it looks bad on other themes we can change it.

**Comment by Bajoja** [comment]
@OzymandiasTheGreat my bad, i figure it out that maybe a icon theme problem, is not necessary change that.

**Comment by OzymandiasTheGreat** [comment]
@Bajoja Nah, it's a minor change. Reload icon also looks fine, so if it looks better on more themes I think that's a good thing and we should change it.

**Comment by Bajoja** [comment]
Very ugly on my system, but i test it with numix and looks great.
ugly

**Comment by OzymandiasTheGreat** [comment]
@Bajoja Yeah, that is not very pretty. I'll change it.

**Comment by Bajoja** [comment]
Ok

**Pull request merged**
