### PR TITLE
tray staus icons ubuntu-mono-dark & ubuntu-mono-light (22px, 24px)

### PR DESCRIPTION
**Pull request by varlesh**
Need update build CMake

### CODE REVIEW

**Comment by varlesh** [comment]
@Bajoja Also for Adwaita (Gnome) we can create symbolic icons... but need use as fallback icon, because some DE not support support symbolic icons on panel (Unity, Pantheon and etc)...
For example, if smartphone-connected not available (not use ubuntu-mono-dark icon theme) use smartphone-connected-symbolic.
It's possible?

**Comment by varlesh** [comment]
I can add symbolic icon for Adwaita. Needed?

**Comment by varlesh** [comment]
Or only white #ffffff for Adwaita... because hicolor icon theme depend and already available icons... hm

**Comment by Bajoja** [comment]
Great, as soon as possible I'll update cmake.

**Comment by varlesh** [comment]
Ok...  only i don't know how better use icons for Gnome DE. Need think about that

**Comment by Bajoja** [comment]
I'm not very familiar with this things of  icons but i will see what we can do for DE that not support symbolic icons on panel.

**Comment by varlesh** [comment]
ubuntu-mono - it'snot symbolic icons. This icons wiil be show on Unity, Pantheon, XFCE and etc ... and Gnome too, but for Gnome and Mint on panel better use symbolic icons (because it's standart). 
Or do not mention it :) Gnome and Cinnamon user can change icon from your self (because not hardcoded and possible).
Also need add depend `ubuntu-mono` on Debian control

**Comment by varlesh** [comment]
@Bajoja Icons not hardcoded (users can create icons for your self), update CMake and add depend `ubuntu-mono`... it's all

**Pull request merged**
